### ISSUE TITLE
Joins

### ISSUE THREAD

**Issue by memcmahon** [turingschool/curriculum-site#101]
Existing Lesson - https://backend.turing.edu/module2/lessons/joins

- [ ] Add a calendar event for the homework/pre-work to the calendar.
- [ ] Add this lesson, and the linked resource at the bottom of the lesson to the SE curriculum page.
- [ ] Review for necessary updates

**Comment by juliet-e** [comment]
We don't need Joins 2 -- just Joins 1 for Mod 2!
