### ISSUE TITLE
Mod 2 Group Project

### ISSUE THREAD

**Issue by memcmahon** [turingschool/curriculum-site#104]
The Big Idea - 'one' project that builds up to a storefront application.

Part 1: A static site similar to [Hang In There](https://frontend.turing.edu/projects/module-1/hang-in-there-v2.html) but with added functionality.  [This separate ticket](https://github.com/turingschool/curriculum-site/issues/149) has been created for this project. 

Part 2: Starting with a rails starter with Part 1 complete, add a rails backend that will store posters for the store in a database. (1 table)

Part 3: Add Customers and Orders to the store (2 tables)

Part 4: Extension to add either a new table, or update a table (like adding address, shipping status, etc...)

**Comment by juliet-e** [comment]
Part 2 starter [here](https://github.com/turingschool-examples/little-shop-se)

**Comment by juliet-e** [comment]
UPDATE 7/5: This card will focus primarily on the Group Project
