### ISSUE TITLE
Revise Dog Party as Mod 2 intermission work in html/css/js

### ISSUE THREAD

**Issue by hfaerber** [turingschool/curriculum-site#127]
## Dog Party

Revise this old FE project [Dog Party](https://github.com/turingschool/front-end-curriculum/blob/gh-pages/projects/archive/dog-party-js-edition.md) to give students a taste working with HTML and CSS and DOM manipulation.  Ideal this will be laid out in a sort of step-by-step tutorial similar to FE M3's ideabox (but maybe without the answers)

Students should have to add onto some existing HTML  and CSS to accomplish some specific goals.  For example:
- change a background color
- add border radius
- maybe use flexbox to lay some elements out a certain way
- add class/ids to HTML?  Maybe add a div around some elements so flexbox can be applied to its children?
- add some html elements and style them?

The Mod 2 Intermission Work ticket #103 relies on this ticket being completed.

**Comment by hfaerber** [comment]
@niksseif 

I believe the existing Dog party spec asks them to not use flexbox and to use float, etc instead.  I definitely think they SHOULD use flexbox rather than doing layout things with float.   Or, they shouldn't worry about layout things at all in this project.

**Comment by niksseif** [comment]
I need to add JS to this PR
