### ISSUE TITLE
[async] How the Web Works I

### ISSUE THREAD

**Issue by memcmahon** [turingschool/curriculum-site#130]
- [x] Copy [this lesson](https://backend.turing.edu/module2/lessons/how_the_web_works_http) to SE curriculum-site
  - [x] Review for potential changes
- [x]  Copy [the exit ticket](https://docs.google.com/forms/d/e/1FAIpQLSdIbdNECk9kzyoVsuxotvWQ520QhBjgcm17WiaBZk3EDHM3RQ/viewform) to the [SEM2 Drive](https://drive.google.com/drive/folders/17C6x_bMbVnpH0-mExFvj5enR6sTV10rE)
- [ ] Update links on the [SEM2 Calendar](https://calendar.google.com/calendar/u/0?cid=Y182ZmJhMWJmOGYxNDNiMDU2MGY5MGUwMDVlOWFlN2RiNmVmN2QyNTIyYTU5NjMxMjE2OTczNjVhMzQxY2RmODljQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20) - Wed, Week 2

**Comment by jamisonordway** [comment]
I started working on this then moved it back to the To-Do column because I don't think I have permission to edit the SEM2 Calendar, but the exit ticket has been copied to [this drive](https://drive.google.com/drive/folders/17C6x_bMbVnpH0-mExFvj5enR6sTV10rE).
