### ISSUE TITLE
How the Web Works II

### ISSUE THREAD

**Issue by memcmahon** [turingschool/curriculum-site#132]
Existing Lesson: https://backend.turing.edu/module2/lessons/request_response_anatomy

- [ ] Move to SE Curriculum site
- [ ] Update Calendar Event (week 2)

**Comment by juliet-e** [comment]
Note: We've been using slides in BE 2 for this lesson that discussed deployment as students were learning about deployment at this point. I think we should probably not introduce deployment at this point in SE2. I think they could explore that in their group project
