### ISSUE TITLE
Create M2 Final Project

### ISSUE THREAD

**Issue by juliet-e** [turingschool/curriculum-site#151]
Builds off the Little Shop group project (which has a BE and FE).  Final will be mostly Rails practice with a one to many relationship plus a small amount of FE

BE: (Erin)
Coupon table with merchant id; endpoints to crud coupons; some db operations (ex: discounted prices)

Front End: (Kayla)
Group project starting point: 
Students will continue to build off the same FE they used for the Group project.  In the group project,  the FE only has CRUD functionality for the merchants.  Merchants are displayed, can be edited, deleted, and new merchants can be added.   Users can view all the items for a specific merchant.

Final Project FE requirements to add onto what they have from the group project:
Students should build out the following:
- Users can click on a merchant (or a button for a given merchant) and see all the coupons for that merchant.  No edit/add/delete functionality needed.  
- We could provide a comp (or a few comp options) for the display of the merchant coupons might look like.  If design isn't their strong suit, we don't want those visual design decisions jamming them up when that isn't a learning goal.
- We should provide the code for the fetch GET request, including that data in the Promise.All, adding it to a global variable.  Students will simply access data through the global variable and display it on the DOM.
- Rather than having this already built into the boilerplate, the spec could walk them through copy.pasting the relevant code into their FE application's existing code.  This forced them to give attention to the network requests without having the challenge of putting it together themself.  As part of their eval, they could be required to describe what is happening in the provided code they copy/pasted into their application.

**Comment by epintozzi** [comment]
Coupon table with merchant id; endpoints to crud coupons; some db operations (ex: discounted prices)
