### ISSUE TITLE
How the Web Works II - Merge Launch intro to APIs

### ISSUE THREAD

**Issue by juliet-e** [turingschool/curriculum-site#164]
- [x]  Move to SE Curriculum site
- [x] Make updates based on learning goals
- [ ] Update Calendar Event (week 2)

NEW LEARNING GOALS:
- Review the structure of a HTTP Request, and HTTP Response
- Describe how users/clients send information through a request - body, path, query parameters
- Introduce the concept of an API as a type of server at a conceptual level
- Introduce JSON
- Practice requests to an existing API - using Postman

Update this lesson plan to adhere to these learning goals. We can use parts of the Launch lesson on Intro to APIs [here](https://launch.turing.edu/module4/lessons/Week2/IntroToAPIs) for the last 3 learning goals.

Note: Deployment doesn't need to be discussed here

**Comment by abdulredd** [comment]
No access to calendar :(
