### ISSUE TITLE
M3 ICs/Assessments

### ISSUE THREAD

**Issue by juliet-e** [turingschool/curriculum-site#239]
FINAL ASSESSMENT/PROJ:
Week 6 Monday morning kick-off
- "take-home" style - 12 hours of worktime on Monday and Tuesday, live evals on Wednesday
- BE API that performs CRUD app
- FE React app that will consume API endpoints to allow users to CRUD
- ** Focus on presentation: design choices, planning, areas for refactoring **

MID MOD
- practice talking through a project of your choice in groups
- Discuss planning, design choices, areas for refactoring
- students will practice giving each other feedback, instructors also give feedback

This card will include
- [ ] Creating spec for take home with project requirements
- [ ] Creating rubric (adapt from Mod 4 take-home, maybe beef up technical quality area?)
- [ ] Create page to describe Mid Mod practice session for student reference

Notes from our M3 planning meeting can be found [here](https://www.notion.so/turingschool/SE-Mod-3-Notes-8c096e729cd641db9638f3b8cba1e183?pvs=4#b29801974f674aa0b38732065c885dd5)

**Comment by epintozzi** [comment]
Consider formatting rubric like common tech interview rubrics?
Example: https://www.techinterviewhandbook.org/coding-interview-rubrics/
