### ISSUE TITLE
Revise Lite Brite Try Coding

### ISSUE THREAD

**Issue by hfaerber** [turingschool/curriculum-site#253]
Work through this [Lite Brite Try Coding Workshop](https://try.turing.edu/popup-lite-brite/) to make it ready to teach as our rebranded "Intro to Web Development workshop"

- [ ] find where the repo indicates "Turing's second shift program" that shows up in Slack previews for this link and remove that (see image in comments)
- [ ] move the starter repo into CodePen instead of repl
- [ ] update the instructions and screengrabs to reflect codepen
- [ ] when finished, update this Try Turing Eve Guide page to reflect that we're now using litebrite

**Comment by hfaerber** [comment]
![Image](https://github.com/user-attachments/assets/c1deb705-ff1e-4e78-8411-e0986ecf2ec7)

**Comment by memcmahon** [comment]
[ ] Condense each try coding content to use only one repl.   Students can copy/paste code from lesson into that one repl rather than opening new repls for different segments.
  * Need to add directions for commenting out old code.
