### ISSUE TITLE
Personal Portfolio Site

### ISSUE THREAD

**Issue by kaylagordon** [turingschool/curriculum-site#305]
Create a spec page outlining the expectations for the portfolio site. Terminal is being removed.

Here is what we have in the current M4 curriculum regarding the portfolio:

Deliverable #1: Complete Personal portfolio
Students may choose to build a custom personal portfolio OR build a portfolio using the provided [template](https://github.com/turingschool/portfolio-template)
Add at least 2 projects and use [these guidelines](https://docs.google.com/document/d/1zKePxhD-xQdLRPeLI21E71ET_U88ZZ-SKTQjRVzs8tM/edit) to help you create the descriptions
Upload your polished and targeted resume
Include the link to your LinkedIn that is updated and optimized for job search
Due date #1: Friday of Week 4. Make sure to [submit for review](https://docs.google.com/forms/d/e/1FAIpQLSfosoD_3cCQD00iFGJCLs7aGdgT50sKzCvof9xKxEDdDAgDBg/viewform) by this date.
We will review and send follow-up on anything to be completed or changed before it is considered complete.

**Comment by epintozzi** [comment]
Should be kicked off as intermission work.

**Comment by juliet-e** [comment]
Add starting directions in intermission work? What should they get done in week 1?

**Comment by epintozzi** [comment]
@juliet-e Here's [the PR](https://github.com/turingschool/curriculum-site/pull/336) for the requirements. I anticipate this being kicked off during the intro to Mod 4, but ideally that linked PR should be enough instruction in case they miss it or are otherwise checked out. Unless I'm misunderstanding your question.

**Comment by epintozzi** [comment]
Side note: this issue seemed to auto close when I put up my PR.
