### ISSUE TITLE
Case Study Assignment

### ISSUE THREAD

**Issue by kaylagordon** [turingschool/curriculum-site#306]
- [x] Move all Case Study files over to curriculum site
- [x] Update spec for clarity as needed
- [x] Remove or update the Final Presentation guidelines (the final presentation will now be focused on their stretch tech project)

Spec Page: https://mod4.turing.edu/projects/employer_case_study/index.html

**Comment by epintozzi** [comment]
There are a bunch of google docs and various links nested within all the pages of this project. Give yourself some time to ensure everything is added to site and copied over correctly.
