### ISSUE TITLE
Analyzing Tech Challenges Lesson

### ISSUE THREAD

**Issue by kaylagordon** [turingschool/curriculum-site#307]
Add slides to curriculum site so we don't lose them: https://docs.google.com/presentation/d/1zFpcHCpDzMB1YJOHB2XBcAkdJQIifDS6Lx6pgKx--bk/edit#slide=id.g1c033f9cd5_0_35

**Comment by epintozzi** [comment]
There are a ton of resources (some duplicates) in the lessons folder for this in drive. It's going to take a little time to parse through and probably should be turned into an actual lesson plan.
