### ISSUE TITLE
Big 0 Lesson

### ISSUE THREAD

**Issue by kaylagordon** [turingschool/curriculum-site#308]
- [ ]  Move lessons to curriculum site 
- [ ] Confirm with team which lessons need to be moved over (there are currently 3)

https://mod4.turing.edu/lessons/cs/big-o.html
https://mod4.turing.edu/lessons/cs/big-o-part-ii.html
https://mod4.turing.edu/lessons/cs/sorting_bigo.html

**Comment by epintozzi** [comment]
For the last year+ we've only taught the first lesson listed (https://mod4.turing.edu/lessons/cs/big-o.html). Either skip the other 2 or list them under Additional Resources.
