### ISSUE TITLE
Grouping & Aggregating Lesson

### ISSUE THREAD

**Issue by kaylagordon** [turingschool/curriculum-site#313]
- [ ]  Move lesson to curriculum site: https://backend.turing.edu/module2/lessons/grouping_and_aggregating
- [ ] No updates listed, but double check that lesson is appropriate given new program changes

**Comment by epintozzi** [comment]
It's a little unclear because I don't see it in the lesson plan, but I think this uses the set list repo. At the very least we probably want to add that to the lesson.
