### ISSUE TITLE
Create async lessons about non-dev roles

### ISSUE THREAD

**Issue by kaylagordon** [turingschool/curriculum-site#320]
- [ ] Create several lessons (async or live) that inform students about non-dev roles they can apply for out of Turing. 

- Support Engineer
- DevOps
- Developer Advocate
- QA
- Technical Writer
- Product Manager
- Sales/Solutions Engineer
- or any other tech adjacent role

Would be awesome to get alumni to speak to these roles

- [x] Ensure these lessons are on the calendar

**Comment by epintozzi** [comment]
[Folder in drive](https://drive.google.com/drive/folders/13v6QB9csiIOOgLZxDGmMzzZzJcS2PeuS?usp=drive_link) for slide shows and resources

**Comment by epintozzi** [comment]
Notes from Kayla in Slack:
Product owner with a lot of great insight: 
[@Josephine Heidepriem](https://turingschool.slack.com/team/U03MAMUUXLY)
https://www.linkedin.com/in/josephine-heidepriem/

(https://turingschool.slack.com/archives/C0738ETMD88/p1730734772658809?thread_ts=1730734593.987209&cid=C0738ETMD88)

Recorded panel on non-traditional dev roles (mostly support engineering): https://www.youtube.com/watch?v=W11otFE-xWI&list=PL1Y67f0xPzdOmktyQlnqVEIRpbTx_apNm&index=3
(https://turingschool.slack.com/archives/C0738ETMD88/p1730734828976759?thread_ts=1730734593.987209&cid=C0738ETMD88)

Looks like we have some folks in DevOps:

(https://turingschool.slack.com/archives/C0738ETMD88/p1730734929988189?thread_ts=1730734593.987209&cid=C0738ETMD88)
DevRel:
![Image](https://github.com/user-attachments/assets/34edc554-c270-4f21-9c6f-99eba3c2c972)
![Image](https://github.com/user-attachments/assets/3a720773-66d9-44be-bc4d-8062c9cd4195)


(https://turingschool.slack.com/archives/C0738ETMD88/p1730735061240829?thread_ts=1730734593.987209&cid=C0738ETMD88)

It would be cool to record like a 30 min convo with 1 or 2 people from each role and then each week students:
1) watch the video
2) spend 20ish min just browsing jobs posted for that role
3) submit reflections (What would I like about this role? What would be challenging? How does my pervious experience lend itself to a role like this?)


Juliet Eyraud
We could invite Zoe and Ian back to talk about being a Solutions Engineer!




Kayla Gordon
(https://turingschool.slack.com/archives/C0738ETMD88/p1730736084565949?thread_ts=1730734593.987209&cid=C0738ETMD88)
[@Eric Weissman](https://turingschool.slack.com/team/U83NHA41G)
 is a program manager
(https://turingschool.slack.com/archives/C0738ETMD88/p1730736103143619?thread_ts=1730734593.987209&cid=C0738ETMD88)
Also, I'm more than happy to talk about support engineering if we want a more direct convo versus the panel discussion

**Comment by epintozzi** [comment]
* What's your day to day like
* How did you get to this role
*

**Comment by muydanny** [comment]
Taking this on! The curriculum draft lives in the notion under Marketing/Alumni Spotlight. Breaking it down into four lessons:

1. Customer Support and Success		
- Support/Customer Success		
- Technical Success / Solutions Architect		
2. Technical Writing and Data Analysis
- Data Quality Analyst		
- Docs Engineer/ Tech Writer		
3. Operations and Reliability		
- Site Reliability Engineer (SRE)		
- Tech Manager		
4. Education and Community Content		
- DevRel
- Instructor
