### ISSUE TITLE
Update Capstone Project

### ISSUE THREAD

**Issue by kaylagordon** [turingschool/curriculum-site#321]
Update the current Capstone Project to be rooted in existing codebases. 

There are lots of notes about these changes [here](https://www.notion.so/turingschool/2410-W1-Mod-4-Planning-10e0ef35707881e8be31d4ae36748328) and full discussion can be found in [this recording](https://turingschool.slack.com/files/UJ2H4M63A/F07R6FSSK35/video1141639882.mp4) (messaged 10/9 in #software-engineering-program)

**Comment by epintozzi** [comment]
Also need to create some starter issues, wireframes, and a starter repo for this first group ahead of Day 1
