### ISSUE TITLE
File IO

### ISSUE THREAD

**Issue by memcmahon** [turingschool/curriculum-site#37]
Existing Lesson: [CSV Walkthrough](https://github.com/turingschool/curriculum-site/blob/main/module1/lessons/csv_walkthrough.md)

Updates:
* Update lesson with more general File IO concepts
* Update language to general programming concepts.
* Add JS examples to 'peek' into another language.

**Comment by hfaerber** [comment]
@memcmahon 
The calendar event for this lesson also includes a link to the [EventManager Tutorial Lesson](https://backend.turing.edu/module1/projects/eventmanager) on the BE site.  Do we want to bring this over to the SE site as well?  Or remove the reference to this?

If we do want to move that over to the SE, could you please do that as part of this ticket?

**Comment by hfaerber** [comment]
[This PR ](https://github.com/turingschool/curriculum-site/pull/156) moves the Event Manager lesson over to SE Curriculum, removes it from the calendar and links it as extra practice at the end of the File IO lesson.   Also corrects link from BE Mod 1 big repo to the SE Mod 1 Big repo
