### ISSUE TITLE
Design Principles

### ISSUE THREAD

**Issue by memcmahon** [turingschool/curriculum-site#38]
Existing Resource: [Design Principles](https://www.google.com/url?q=https://docs.google.com/presentation/d/1J55751_ZSPJMqQW-Fse1EFTRkjAWOvWmaNjgXev-9GQ/edit?usp%3Dsharing&sa=D&source=calendar&ust=1715442558731789&usg=AOvVaw2y8x2XyRq3hbwcHoErEuCo)

Updates:
* Needs a lesson plan

**Comment by kaylagordon** [comment]
This may be the lesson plan? https://github.com/turingschool/curriculum-site/blob/main/module1/lessons/design_principles.md
