### ISSUE TITLE
How to Use AI as a Dev

### ISSUE THREAD

**Issue by kaylagordon** [turingschool/curriculum-site#42]
New lesson! Create a lesson for Week 4 M1 that shows students how to effectively use chatGPT to help them be more effective devs/students. 
- If a lesson was confusing, what questions can you ask chatGPT?
- if you want more practice using enumerables, how can chatGPT help with that?

**Comment by hfaerber** [comment]
After merging Kayla's PR with the initial lesson, I created this PR to fix a typo and add styling.
