### ISSUE TITLE
HTML Fundamentals

### ISSUE THREAD

**Issue by memcmahon** [turingschool/curriculum-site#85]
Existing Lesson - https://frontend.turing.edu/lessons/module-1/html-fundamentals.html

* Add lesson to curriculum site
* Review for possible updates

**Comment by cjsim89** [comment]
*NOTE* This lesson refers to 2 other resources currently in the FE curriculum: 

* [Chrome Dev Tools](https://frontend.turing.edu/lessons/module-1/chrome-dev-tools)
* [HTML Structure, Semantics](https://frontend.turing.edu/lessons/module-1/html-semantic-element-review.html?_ga=2.84629081.1739922120.1717528769-343374822.1704738512)

**Comment by cjsim89** [comment]
I'm going to transfer the lessons over to the SE program folders just like normal, but leave them under "Additional Resources" for now, if we aren't dedicating classes to them (don't see a card for them right now).

**Comment by cjsim89** [comment]
**FURTHER NOTE:**

The lesson on `html_semantic_element_review` refers to a link called "independent Study" on the FE website that is an index of other FE-specific resources .... not sure what to do with that.
