### ISSUE TITLE
SQL & AR - Basic

### ISSUE THREAD

**Issue by memcmahon** [turingschool/curriculum-site#96]
Existing Lesson - https://backend.turing.edu/module2/lessons/sql_and_active_record

- [ ] Add to curriculum site
- [ ] Update the Review Intermission Work section

**Note**
This issue is related to #93 #94 #95.  These lessons should create/build on the [Set List](https://github.com/turingschool-examples/set-list-7) application

**Comment by juliet-e** [comment]
At this point, students will not know about one-to-many relationships, so we should just make sure this lesson doesn't use resources that have foreign keys/db relationships yet. Or minimal exposure. Focus on the basic operations and examples that use one single db table
